# Site settings
title: Malizma's LRWeb Mods
baseurl: "/linerider-userscript-mods"
url: "https://malizma333.github.io"
repository: Malizma333/linerider-userscript-mods

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-target-blank